### ISSUE TITLE
proxy password error

### ISSUE THREAD

**Issue by bugxch** [wakatime/komodo-wakatime#10]
I am encounter the similar issue as before in Proxy error with VS code. I install wakatime and input my proxy configuration, but it reminds me the error of `configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%40feng@proxyus.feng.com:8080'`.

I think it is because that there is a special character in my pass word, the native pass word is `1234@feng`, and I translate it into url format with `1234%40feng`, so how to handle the password in wakatime proxy? such as native `https://jason:1234@feng:proxyus.feng.com:8080`?

**Comment by alanhamlett** [comment]
I'm assuming you tried without url encoding (no percent sign just `1234@feng`) and it doesn't work?

**Comment by bugxch** [comment]
> I'm assuming you tried without url encoding (no percent sign just `1234@feng`) and it doesn't work?

Thanks for your reply and it works~

**Comment by bugxch** [comment]
> I'm assuming you tried without url encoding (no percent sign just `1234@feng`) and it doesn't work?

thank you for your reply and it works
