### ISSUE TITLE
Support for Komodo/Edit 9

### ISSUE THREAD

**Issue by robmercier00** [wakatime/komodo-wakatime#7]
Komodo and Komodo Edit 9 have been released, it would be awesome if wakatime would support it.

**Comment by alanhamlett** [comment]
Added with #8 and #5 in v2.0.1

**Comment by robmercier00** [comment]
I've downloaded v2.0.1.xpi and I'm still getting a "(null) is incompatible with Komodo Edit 9.0.0" message... any ideas what I might be missing?

**Comment by robmercier00** [comment]
Scratch that. It's working now. Thanks!
