### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by mickey263** [wakatime/komodo-wakatime#9]
Hello,

komodo plugin can't connect to server with my company proxy.
I am getting this error : 

{"now": "2016/12/05 13:39:46 Paris, Madrid", "version": "6.0.3", "plugin": "komodo-wakatime/3.0.4", "time": 1480941584.412, "caller": "C:\\Users\\X.X\\AppData\\Local\\ActiveState\\KomodoIDE\\10.1\\XRE\\extensions\\wakatime@wakatime.com\\components\\wakatime\\main.py", "lineno": 385, "file": "C:\\Users\\X.X\\.wakatime.log", "level": "WARNING", "message": {**"SSLError": "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)**", 

i tried both http/https.

**Comment by alanhamlett** [comment]
Does setting a proxy in your `~/.wakatime.cfg` file help? Here is an example showing the expected proxy format:
https://github.com/wakatime/wakatime#configuring

**Comment by mickey263** [comment]
I 've already try it without success with the format :  proxy = https://user:pass@localhost:8080

**Comment by alanhamlett** [comment]
The release today adds support for SOCKS and NTLM proxies. Does v3.0.5 work with your proxy?

**Comment by alanhamlett** [comment]
Also related, you can now disable SSL verification when behind a corp proxy by adding this new line to your `~/.wakatime.cfg` file:
`no_ssl_verify = true`

**Comment by mickey263** [comment]
Thanks for your reply.
I will test it asap.

Greetings
